// This file is autogenerated by hidl-gen. Do not edit manually.
// Source: vendor.hardkernel.hardware.odroidthings@1.0
// Location: vendor/hardkernel/interfaces/odroidthings/1.0/

#ifndef HIDL_GENERATED_VENDOR_HARDKERNEL_HARDWARE_ODROIDTHINGS_V1_0_EXPORTED_CONSTANTS_H_
#define HIDL_GENERATED_VENDOR_HARDKERNEL_HARDWARE_ODROIDTHINGS_V1_0_EXPORTED_CONSTANTS_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    DIRECTION_IN = 0,
    DIRECTION_OUT_INITIALLY_HIGH = 1, // (::vendor::hardkernel::hardware::odroidthings::V1_0::Direction.DIRECTION_IN implicitly + 1)
    DIRECTION_OUT_INITIALLY_LOW = 2, // (::vendor::hardkernel::hardware::odroidthings::V1_0::Direction.DIRECTION_OUT_INITIALLY_HIGH implicitly + 1)
} direction_t;

typedef enum {
    PIN_PWR = 1, // (1 << 0)
    PIN_GND = 2, // (1 << 1)
    PIN_GPIO = 4, // (1 << 2)
    PIN_AIN = 8, // (1 << 3)
    PIN_PWM = 16, // (1 << 4)
    PIN_I2C_SDA = 32, // (1 << 5)
    PIN_I2C_SCL = 64, // (1 << 6)
    PIN_SPI_SCLK = 128, // (1 << 7)
    PIN_SPI_MOSI = 256, // (1 << 8)
    PIN_SPI_MISO = 512, // (1 << 9)
    PIN_SPI_CE0 = 1024, // (1 << 10)
    PIN_UART_RX = 2048, // (1 << 11)
    PIN_UART_TX = 4096, // (1 << 12)
    PIN_ETC = 8192, // (1 << 13)
} pin_mode;

#ifdef __cplusplus
}
#endif

#endif  // HIDL_GENERATED_VENDOR_HARDKERNEL_HARDWARE_ODROIDTHINGS_V1_0_EXPORTED_CONSTANTS_H_
